name: TEST

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: TEST-ENV
      url: https://google.com
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo secret ${{ secrets.TEST_ENV_KEY }}
